name: Juliobevione.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#5D347A'
    - '#12A9C6'
    - '#AE98BC'
    - '#D6CCDD'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.7476344
  rhythmicContrast: 1
purpose: []
