layout_spectrum: 0.849087
color:
  saturation: 0.7476344
  lightness: 0.3914329
  brandStrength: 0.9355329
  brandColors:
    - '#FFFFFF'
    - '#5D347A'
    - '#12A9C6'
    - '#AE98BC'
    - '#D6CCDD'
  rhythmicContrast: 0.8383575
typography_spectrum: 0.320623
name: Juliobevione.com
